json.id @movie.id
json.title @movie.title
json.release_date @movie.release_date
json.actors @movie.actors
json.directors @movie.directors
json.gender @movie.gender.name
json.original_language @movie.original_language
json.duration @movie.duration
json.created_at @movie.created_at
json.updated_at @movie.updated_at